### ISSUE TITLE
个人属性进度条不能正常渲染

### ISSUE THREAD

**Issue by summer-foam** [crrashh1542/my-webfrontend#61]
![image](https://github.com/crrashh1542/crash-homepage/assets/46050179/ee45281f-24a8-41cf-8765-1dfc2e23ad4a)

Proterties.vue中定义的数据中的 value 字段是一个字符串，但它看起来像一个对象字面量，应该是一个样式对象，以设置进度条的宽度。为了解决这个问题，需要对 value 字段进行一些修改
这是修改之后的
`<script>
export default {
  name: "BodyProterties",
  data() {
    return {
      proterty: [
        {
          "item": "智商",
          "value": { width: "40%" }, // 注意这里的 value 是一个对象
          "tip": "偶尔脑袋也会宕机"
        },
        {
          "item": "技术",
          "value": { width: "70%" }, // 注意这里的 value 是一个对象
          "tip": "有，但是不多，会的比大部分人多一点点"
        },
        {
          "item": "社恐",
          "value": { width: "50%" }, // 注意这里的 value 是一个对象
          "tip": "多数时候变成波奇酱，也有时候无"
        },
        {
          "item": "心理状态",
          "value": { width: "60%" }, // 注意这里的 value 是一个对象
          "tip": "抗压能力还是有的，但也有崩溃的时候"
        }
      ]
    }
  }
}
</script>
`

**Comment by summer-foam** [comment]
![image](https://github.com/crrashh1542/crash-homepage/assets/46050179/5536030e-a067-4e63-b86e-8c16d4ab6d7d)
xi修改之后效果

**Comment by crrashh1542** [comment]
妈呀，我这小破项目居然还有大佬来看.... 不胜感激！！
很快就会按照大佬的思路重写的，非常非常非常谢谢啦！

~~主要是项目目前在重写新UI过程中，所以bug多得惊人，见谅~~
~~我滴天我怎么又在画饼~~

**Comment by summer-foam** [comment]
只是写自己主页的时候，没事看了看了Github上面的来找找灵感，看了一下代码发现有错误就指出一下🤔🤔🤔

**Comment by crrashh1542** [comment]
v3中的 1a0ee94 已修复上述内容，暂且算作关闭，需要后续跟进的话麻烦楼主重新开启该issue😊
